pipeline:
  changelog:
    image: quay.io/git-chglog/git-chglog:latest
    secrets: [ ACCESS_TOKEN ]
    commands:
      # clone repository
      - git clone https://"$${ACCESS_TOKEN}"@codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}.git /${CI_REPO_NAME}
      - cd /${CI_REPO_NAME}
      # generate changelog
      - git-chglog > CHANGELOG.md
      # configure git
      - git config --global user.email "mail@ci.codeberg.org"
      - git config --global user.name "Codeberg CI"
      # deploy changelog
      - git add CHANGELOG.md
      - git commit -m "docs(changelog):\ update"
      - git push
    when:
      event: tag
  build-linux:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p build
      - godot -v --export "Linux/X11" build/Dinonuggy\'s\ Journey\ for\ Linux\ v${CI_COMMIT_TAG}.x86_64
      - ls build
    when:
      event: tag
  build-windows:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p build
      - godot -v --export "Windows Desktop" build/Dinonuggy\'s\ Journey\ for\ Windows\ v${CI_COMMIT_TAG}.exe
      - ls build
    when:
      event: tag
  build-mac:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p build
      - godot -v --export "Mac OSX" build/Dinonuggy\'s\ Journey\ for\ macOS\ v${CI_COMMIT_TAG}.zip
      - ls build
    when:
      event: tag
  build-web:
    image: barichello/godot-ci
    commands:
      - mkdir -v -p build/Dinonuggy\'s\ Journey\ for\ Web\ v${CI_COMMIT_TAG}
      - godot -v --export "HTML5" build/Dinonuggy\'s\ Journey\ for\ Web\ v${CI_COMMIT_TAG}/index.html
      - ls build
    when:
      event: tag
  # Android Debug Job. It will use the generated debug.keystore.
  #debug-android:
  #  image: ${BUILD_IMAGE}
  #  commands:
  #    - mkdir -v -p build/android
  #    - godot -v --export-debug "Android Debug" ../build/android/$EXPORT_NAME-debug.apk
  # Android Release Job. You will need to include keystore and password in the GitLab variable settings:
  # 1. Take your generated keystore and convert it to Base64:
  #   Linux & macOS: `base64 release.keystore -w 0`
  #   Windows: `certutil -encodehex -f release.keystore encoded.txt 0x40000001`
  # 2. Go to GitLab Project > Settings > CI/CD > Variables and copy the Base64-encoded keystore value in a new variable `SECRET_RELEASE_KEYSTORE_BASE64` as type variable.
  # 3. Create a second variable SECRET_RELEASE_KEYSTORE_USER as type variable with the alias of your keystore as value.
  # 4. Create a third variable SECRET_RELEASE_KEYSTORE_PASSWORD as type variable with the password of your keystore as value.
  #build-android:
  #  image: ${BUILD_IMAGE}
  #  rules:
  #    - if: $SECRET_RELEASE_KEYSTORE_BASE64
  #    - if: $SECRET_RELEASE_KEYSTORE_USER
  #    - if: $SECRET_RELEASE_KEYSTORE_PASSWORD
  #  commands:
  #    - echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
  #    - mkdir -v -p build/android
  #    - cd $EXPORT_NAME
  #    - sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
  #    - sed 's@keystore/release_user=".*"@keystore/release_user="'$SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
  #    - sed 's@keystore/release_password=".*"@keystore/release_password="'$SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
  #    - godot -v --export "Android" ../build/android/$EXPORT_NAME.apk
  package-web:
    image: alpine
    commands:
      - apk add zip
      - zip build/Dinonuggy\'s\ Journey\ for\ Web\ v${CI_COMMIT_TAG}.zip build/Dinonuggy\'s\ Journey\ for\ Web\ v${CI_COMMIT_TAG}/*
      - rm -rf build/Dinonuggy\'s\ Journey\ for\ Web\ v${CI_COMMIT_TAG}
      - ls build
    when:
      event: tag
  gitea_release:
    image: plugins/gitea-release
    secrets: [ gitea_token token ]
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://codeberg.org
      files:
        - build/*
      checksum:
        - sha256
        - sha512
      title: ${CI_COMMIT_TAG}
      note: ${CI_REPO_LINK}/src/branch/main/CHANGELOG.md#${CI_COMMIT_TAG/\./-}-$(date -u +"%Y-%m-%d")
    when:
      event: tag